---
services:
  webtop:
    image: lscr.io/linuxserver/webtop:ubuntu-kde
    container_name: webtop
    environment:
      - TZ=Asia/Taipei
    ports:
      - 3000:3000
      - 3001:3001
    restart: always
    runtime: nvidia
