version: '3.8'

services:
  open-webui:
    image: ghcr.io/open-webui/open-webui
    container_name: open-webui
    ports:
      - "8080:8080"
    volumes:
      - open-webui:/app/backend/data
    restart: unless-stopped
    privileged: true

volumes:
  open-webui:

